apiVersion: apps/v1
kind: Deployment
metadata:
  name: nominatim-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nominatim
  template:
    metadata:
      labels:
        app: nominatim
        track: canary
    spec:
      volumes:
      - name: nominatim-secret-volume
        secret:
          secretName: nominatim-storage-secret
      containers:
      - name: nominatim-k8s
        image: unifon/nominatim-k8s:latest
        env:
        - name: NOMINATIM_MODE
          value: CREATE
        - name: NOMINATIM_PBF_URL
          value: "http://download.geofabrik.de/europe/norway-latest.osm.pbf"
        - name: NOMINATIM_DATA_LABEL
          value: norway-20201027
        volumeMounts:
        - name: azure
          mountPath: /mnt/azure
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /search
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
      volumes:
      - name: azure
        azureFile:
          secretName: azure-storage-secret
          shareName: storeobelixgermany
          readOnly: false